name: Welcome first-time contributor
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@v4.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-opened-msg: |
            Hi there! Thanks for opening your first issue! We'll get back to you shortly.
            
            While you wait, feel free to join our [Discord community](https://discord.gg/2NabXnQzmv) to chat with us.
          pr-opened-msg: |
            Hi there! Thanks for your first pull request! We'll review it shortly.
            
            While it's getting reviewed, feel free to join our [Discord community](https://discord.gg/2NabXnQzmv) for suggestions and chat.
          labels: "First-Time Contributor"
