name: Welcome first-time contributor
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@v4.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-opened-msg: "Hey @{fc-author}, thanks for opening your first issue! Welcome to the SmoothAPI community!"
          pr-opened-msg: "Hey @{fc-author}, thanks for your first pull request! We'll review this as soon as possible."
          labels: "First-Time Contributor"
